name: test render
on: [push, pull_request]
jobs:
  test_render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/TwitchPlaysPokemon/ttxrenderer.git#egg=ttxrenderer
      - name: Test render teletext
        run: python -m ttxrenderer sample_page test
      - uses: actions/upload-artifact@v4
        with:
          name: combined_image.png
          path: test/combined_image.png